include (../cmake/ExternalProjectHelper)

find_external_project_add(	
	#BUILD_SHARED_LIBRARY
	NAME openssl
	DEPENDS ""
	CONFIGURE_COMMANDS 	-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} 
					   	-DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR} 
						-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	EXPORT_LIBRARIES 	${CMAKE_INSTALL_PREFIX}/lib/libcrypto.a 
						${CMAKE_INSTALL_PREFIX}/lib/libssl.a
	EXTRA_LINKS ""
)