include (../cmake/ExternalProjectHelper)

if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
	find_external_project_add(NAME curl
	    DEPENDS "openssl"
	    CONFIGURE_COMMANDS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DUSE_SYSTEM_SSL=${USE_SYSTEM_SSL} -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR}
	    EXPORT_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/libcurl-d.a)
else()
	find_external_project_add(NAME curl
	    DEPENDS "openssl"
	    CONFIGURE_COMMANDS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DUSE_SYSTEM_SSL=${USE_SYSTEM_SSL} -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR}
	    EXPORT_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/libcurl.a)
endif()
